---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
  nodesecurity:
    enabled: true
  eslint:
    enabled: true
  scss-lint:
    enabled: true
  rubymotion:
    enabled: true

ratings:
  paths:
    - Gemfile.lock
    - "**.erb"
    - "**.rb"
    - "**.js"
    - "**.scss"

exclude_paths:
  - db/
  - test/
  - vendor/
