os: linux
sudo: required
language: ruby

services:
  - docker
  - postgresql
  - redis-server

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

rvm:
  - 2.3.1
  - 2.2.5

env:
  - DB=sqlite
  - DB=postgresql
  - DB=mysql

cache:
  directories:
    - vendor/bundle

before_install:
  - sudo apt-get install -y mysql-server mysql-client
  - cp ci/database.$DB.yml config/database.yml
  - psql  -c 'create database travis_ci_test;' -U postgres
  - mysql -e 'create database travis_ci_test;' -u root

install:
  - bundle install --jobs 2 --path vendor/bundle

before_script:
  - bundle exec rails db:migrate RAILS_ENV=test

script:
  - "CODECLIMATE=true bundle exec rspec"
