language: ruby

rvm:
  - 2.3.1
  - 2.2.5

cache:
  directories:
    - vendor/bundle

install:
  - bundle install --jobs 2 --path vendor/bundle

before_script:
  - bundle exec rails db:migrate RAILS_ENV=test

script:
  - "CODECLIMATE=true bundle exec rspec"
