os: linux
sudo: required
language: ruby

services:
  - docker
  - postgresql
  - redis-server

rvm:
  - 2.3.1
  - 2.2.5

env:
  - DB=sqlite
  - DB=postgresql
# FIXME: It doesn't work well.
#  - DB=mysql

cache:
  directories:
    - vendor/bundle

before_install:
  - sudo apt-get install -y mysql-server mysql-client
  - cp ci/database.$DB.yml config/database.yml
  - psql  -c 'create database travis_ci_test;' -U postgres
# FIXME: It doesn't work well.
#  - mysql -e 'create database travis_ci_test;'

install:
  - bundle install --jobs 2 --path vendor/bundle

before_script:
  - bundle exec rails db:migrate RAILS_ENV=test

script:
  - "CODECLIMATE=true bundle exec rspec"
